name: SLSA 3 Publish Package to npmjs

on:
 release:
   types: [created]
 workflow_dispatch:

permissions: read-all

jobs:
  build:
    permissions:
      contents: read
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v1.6.0-rc.0
    with:
      access: public
      npm-publish: true
      run-scripts: ci, build
    secrets:
      node-auth-token: ${{ secrets.NPM_TOKEN }}
